"""
apps/analytics/serializers.py
──────────────────────────────
Serializers for Analytics API endpoints.
"""

from rest_framework import serializers


class DishPerformanceItemSerializer(serializers.Serializer):
    product_name = serializers.CharField(
        help_text="Name of the sold dish/product."
    )
    quantity_sold = serializers.IntegerField(
        help_text="Total quantity sold during the period."
    )
    total_sales = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Total revenue generated by this dish."
    )
    theoretical_cost = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Total theoretical ingredient cost for quantity sold."
    )
    gross_profit = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Gross profit generated by this dish."
    )
    margin_pct = serializers.DecimalField(
        max_digits=5, decimal_places=2,
        help_text="Profit margin percentage."
    )


class DashboardSummarySerializer(serializers.Serializer):
    restaurant_id = serializers.UUIDField(
        help_text="UUID of the restaurant."
    )
    restaurant_name = serializers.CharField(
        help_text="Name of the restaurant."
    )
    start_date = serializers.DateField(
        help_text="Start date of the analyzed period."
    )
    end_date = serializers.DateField(
        help_text="End date of the analyzed period."
    )
    total_revenue = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Total revenue generated during the period."
    )
    total_cost = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Total cost during the period."
    )
    gross_profit = serializers.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Gross profit (total_revenue - total_cost)."
    )
    food_cost_pct = serializers.DecimalField(
        max_digits=5, decimal_places=2,
        help_text="Food cost percentage of total revenue."
    )
    profit_margin_pct = serializers.DecimalField(
        max_digits=5, decimal_places=2,
        help_text="Profit margin percentage."
    )
    days = serializers.IntegerField(
        help_text="Total days analyzed."
    )


class DashboardAnalyticsResponseSerializer(serializers.Serializer):
    summary = DashboardSummarySerializer()
    dish_performance = DishPerformanceItemSerializer(many=True)


class DishPerformanceAnalyticsResponseSerializer(serializers.Serializer):
    restaurant_id = serializers.UUIDField(
        help_text="UUID of the restaurant."
    )
    restaurant_name = serializers.CharField(
        help_text="Name of the restaurant."
    )
    start_date = serializers.DateField(
        help_text="Start date of the analyzed period."
    )
    end_date = serializers.DateField(
        help_text="End date of the analyzed period."
    )
    dish_performance = DishPerformanceItemSerializer(many=True)
