# Generated by Django 6.1.1 on 2026-09-09 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('REAUTH_REQUIRED', 'Reauthorization Required'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], db_index=True, default='DISCONNECTED', max_length=20)),
                ('requires_reauthorization', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, default='', max_length=200)),
                ('business_location_id', models.CharField(blank=True, default='', max_length=200)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lightspeed_config', to='locations.location')),
            ],
            options={
                'verbose_name': 'Lightspeed Configuration',
                'verbose_name_plural': 'Lightspeed Configurations',
            },
        ),
    ]
