# Generated by Django 6.1.1 on 2026-09-19 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_lightspeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedAppCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series', models.CharField(choices=[('k_series', 'Lightspeed K-Series'), ('l_series', 'Lightspeed L-Series')], db_index=True, help_text='The Lightspeed product series (e.g. K-Series or L-Series).', max_length=20, unique=True)),
                ('client_id', models.CharField(help_text='OAuth Client ID provided by Lightspeed.', max_length=255)),
                ('client_secret', models.CharField(help_text='OAuth Client Secret provided by Lightspeed.', max_length=255)),
                ('redirect_uri', models.CharField(help_text='Registered OAuth Redirect URI.', max_length=500)),
                ('auth_url', models.URLField(default='https://cloud.lightspeedapp.com/oauth/authorize.php', help_text='OAuth authorization endpoint.', max_length=500)),
                ('token_url', models.URLField(default='https://cloud.lightspeedapp.com/oauth/access_token.php', help_text='OAuth token exchange and refresh endpoint.', max_length=500)),
                ('api_base_url', models.URLField(default='https://api.ikentoo.com', help_text='Base URL for REST API endpoints.', max_length=500)),
                ('scope', models.CharField(blank=True, default='employee:all', help_text='OAuth scopes requested.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential configuration is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lightspeed App Credential',
                'verbose_name_plural': 'Lightspeed App Credentials',
                'ordering': ['series'],
            },
        ),
        migrations.AddField(
            model_name='lightspeedconfig',
            name='series',
            field=models.CharField(choices=[('k_series', 'Lightspeed K-Series'), ('l_series', 'Lightspeed L-Series')], db_index=True, default='k_series', help_text='The Lightspeed series configured for this restaurant location.', max_length=20),
        ),
    ]
