# Generated by Django 6.1.1 on 2026-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin')], default='RESTAURANT_ADMIN', max_length=20),
        ),
    ]
