# Generated by Django 6.1.1 on 2026-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_change_required_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
