# Generated by Django 6.1.1 on 2026-09-09 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('base_unit', models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('pcs', 'Pieces (pcs)'), ('pack', 'Pack'), ('dozen', 'Dozen')], default='g', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_stock_alert', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('latest_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_per_base_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='locations.location')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (L)'), ('pcs', 'Pieces (pcs)'), ('pack', 'Pack'), ('dozen', 'Dozen')], default='g', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entries', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_entries', to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_entries', to='locations.location')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
