# Generated by Django 6.1.1 on 2026-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_color',
            field=models.CharField(blank=True, default='#10b981', help_text='Fallback hex color shown when no product picture is uploaded (e.g. #ffffff).', max_length=30),
        ),
    ]
