# Generated by Django 6.1.1 on 2026-09-09 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('pass_changed', 'Password Changed'), ('daily_summary', 'Daily Summary'), ('lightspeed_sync_completed', 'Lightspeed Sync Completed'), ('sales_import_completed', 'Sales Import Completed'), ('low_stock_alert', 'Low Stock Alert'), ('profitability_alert', 'Profitability Alert'), ('recipe_updated', 'Recipe Updated'), ('purchase_logged', 'Purchase Logged'), ('menu_item_updated', 'Menu Item Updated'), ('system_alert', 'System Alert'), ('new_user', 'New User Joined')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
